name: Deploy Injector

on: workflow_dispatch

jobs:
  build:
    name: Deploy Wispcraft Injector
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Wispcraft injector
        run: |
          pnpm run build && pnpm run build:injector
          mv dist/injector.html dist/index.html
          rm -rf dist/*.ts dist/connection

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages